import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";
import {useEffect} from "react";
import ResponsiveAppBar from "../components/header/AppBar";

const Home: NextPage = () => {
  //const hello = trpc.example.hello.useQuery({ text: null });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <header>
          <AuthHeader />
        </header>

      </main>
    </>
  );
};

export default Home;

const AuthHeader: React.FC = () => {
  const { data: sessionData } = useSession();

  return (
    <ResponsiveAppBar />
  );
};
