import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import ResponsiveAppBar from "../components/header/AppBar";
import Main from "../components/main/Main";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <meta name="referrer" content="no-referrer" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <header>
          <ResponsiveAppBar />
        </header>
        {sessionData &&
            <Main />
        }
      </main>
    </>
  );
};

export default Home;
